## Part 1: Preprocessing

In [2]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder, OneHotEncoder
import pandas as pd
import numpy as np
from tensorflow.keras.models import Model
from tensorflow.keras import layers

#  Import and read the attrition data
attrition_df = pd.read_csv('https://static.bc-edx.com/ai/ail-v-1-0/m19/lms/datasets/attrition.csv')
attrition_df.head()

2024-11-20 16:58:41.649401: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


Age Attrition     BusinessTravel              Department  DistanceFromHome  \
0   41       Yes      Travel_Rarely                   Sales                 1   
1   49        No  Travel_Frequently  Research & Development                 8   
2   37       Yes      Travel_Rarely  Research & Development                 2   
3   33        No  Travel_Frequently  Research & Development                 3   
4   27        No      Travel_Rarely  Research & Development                 2   

   Education EducationField  EnvironmentSatisfaction  HourlyRate  \
0          2  Life Sciences                        2          94   
1          1  Life Sciences                        3          61   
2          2          Other                        4          92   
3          4  Life Sciences                        4          56   
4          1        Medical                        1          40   

   JobInvolvement  ...  PerformanceRating RelationshipSatisfaction  \
0               3  ...                  3                        1   
1               2  ...                  4                        4   
2               2  ...                  3                        2   
3               3  ...                  3                        3   
4               3  ...                  3                        4   

   StockOptionLevel TotalWorkingYears  TrainingTimesLastYear WorkLifeBalance  \
0                 0                 8                      0               1   
1                 1                10                      3               3   
2                 0                 7                      3               3   
3                 0                 8                      3               3   
4                 1                 6                      3               3   

   YearsAtCompany  YearsInCurrentRole  YearsSinceLastPromotion  \
0               6                   4                        0   
1              10                   7                        1   
2               0                   0                        0   
3               8                   7                        3   
4               2                   2                        2   

   YearsWithCurrManager  
0                     5  
1                     7  
2                     0  
3                     0  
4                     2  

[5 rows x 27 columns]

In [3]:
# Determine the number of unique values in each column.
attrition_df.nunique()

Age                         43
Attrition                    2
BusinessTravel               3
Department                   3
DistanceFromHome            29
Education                    5
EducationField               6
EnvironmentSatisfaction      4
HourlyRate                  71
JobInvolvement               4
JobLevel                     5
JobRole                      9
JobSatisfaction              4
MaritalStatus                3
NumCompaniesWorked          10
OverTime                     2
PercentSalaryHike           15
PerformanceRating            2
RelationshipSatisfaction     4
StockOptionLevel             4
TotalWorkingYears           40
TrainingTimesLastYear        7
WorkLifeBalance              4
YearsAtCompany              37
YearsInCurrentRole          19
YearsSinceLastPromotion     16
YearsWithCurrManager        18
dtype: int64

In [4]:
# Create y_df with the Attrition and Department columns
y_df = attrition_df[['Attrition', 'Department']].copy()


In [5]:
# Create a list of at least 10 column names to use as X data
fields = ['Education',
          'Age',
          'DistanceFromHome',
          'JobSatisfaction',
          'OverTime',
          'StockOptionLevel',
          'WorkLifeBalance',
          'YearsAtCompany',
          'YearsSinceLastPromotion',
          'NumCompaniesWorked']


# Create X_df using your selected columns
X_df = attrition_df[fields].copy()

# Show the data types for X_df
X_df.dtypes


Education                   int64
Age                         int64
DistanceFromHome            int64
JobSatisfaction             int64
OverTime                   object
StockOptionLevel            int64
WorkLifeBalance             int64
YearsAtCompany              int64
YearsSinceLastPromotion     int64
NumCompaniesWorked          int64
dtype: object

In [6]:
# Convert your X data to numeric data types however you see fit
# Add new code cells as necessary
OverTime_encoder = LabelEncoder()
X_df['OverTime'] = OverTime_encoder.fit_transform(X_df['OverTime'])
X_df['OverTime'].value_counts()

OverTime
0    1054
1     416
Name: count, dtype: int64

In [7]:
# Split the data into training and testing sets
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X_df, y_df)

In [8]:
# Create a StandardScaler
X_scaler = StandardScaler()

# Fit the StandardScaler to the training data
X_scaler.fit(X_train)

# Scale the training and testing data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [9]:
X_train_scaled

array([[ 1.07541244, -0.0883721 , -0.15568955, ...,  0.51070349,
        -0.67764287, -0.67006343],
       [ 1.07541244, -0.0883721 ,  1.07332107, ..., -1.00038159,
        -0.67764287,  0.5599364 ],
       [ 0.10081992, -0.95595392, -0.40149167, ..., -0.66458491,
        -0.67764287, -0.67006343],
       ...,
       [ 0.10081992,  1.42989608, -1.01599698, ...,  1.85389023,
        -0.67764287, -1.08006338],
       [ 0.10081992, -0.63061074, -0.77019485, ...,  0.00700846,
         1.54770284, -0.67006343],
       [-0.87377261,  0.3454188 ,  2.05652956, ..., -1.00038159,
        -0.67764287,  0.14993646]])

In [10]:
# Create a OneHotEncoder for the Department column
department_encoder = OneHotEncoder(sparse_output = False)

# Fit the encoder to the training data
department_encoder.fit(y_train[['Department']])

# Create two new variables by applying the encoder
# to the training and testing data
y_train_department = department_encoder.transform(y_train[['Department']])
y_test_department = department_encoder.transform(y_test[['Department']])

y_train_department

array([[0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       ...,
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.]])

In [11]:
# Create a OneHotEncoder for the Attrition column
attrition_encoder = OneHotEncoder(sparse_output = False)

# Fit the encoder to the training data
attrition_encoder.fit(y_train[['Attrition']])

# Create two new variables by applying the encoder
# to the training and testing data
y_train_attrition = attrition_encoder.transform(y_train[['Attrition']])
y_test_attrition = attrition_encoder.transform(y_test[['Attrition']])

y_test_attrition[:5]

array([[0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.]])

## Create, Compile, and Train the Model

In [13]:
# Find the number of columns in the X training data
number_input_features = len(X_train.columns)

# Create the input layer
input_layer = layers.Input(shape = (number_input_features, ), name = 'input')

# Create at least two shared layers
shared1 = layers.Dense(64, activation = 'relu', name = 'shared1')(input_layer)
shared2 = layers.Dense(128, activation = 'relu', name = 'shared2')(shared1)

In [14]:
# Create a branch for Department
# with a hidden layer and an output layer

# Create the hidden layer
department_hidden = layers.Dense(32, activation = 'relu', name = 'department_hidden')(shared2)

# Create the output layer
department_output = layers.Dense(y_test_department.shape[1], activation = 'softmax', name = 'department_output')(department_hidden)


In [15]:
# Create a branch for Attrition
# with a hidden layer and an output layer

# Create the hidden layer
attrition_hidden = layers.Dense(32, activation = 'relu', name = 'attrition_hidden')(shared2)

# Create the output layer
attrition_output = layers.Dense(y_test_attrition.shape[1], activation = 'sigmoid', name = 'attrition_output')(attrition_hidden)


In [16]:
# Create the model
model = Model(inputs = input_layer, outputs = [
    department_output,
    attrition_output
])


# Compile the model
model.compile(optimizer = 'adam',
              loss = {
                  'department_output':'mse',
                  'attrition_output':'mse'
              },
              metrics = {
                  'department_output':['accuracy', 'mse'],
                  'attrition_output':['accuracy', 'mse']
              })

# Summarize the model
model.summary()

Model: "functional"

┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)        ┃ Output Shape      ┃    Param # ┃ Connected to      ┃
┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━┩
│ input (InputLayer)  │ (None, 10)        │          0 │ -                 │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ shared1 (Dense)     │ (None, 64)        │        704 │ input[0][0]       │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ shared2 (Dense)     │ (None, 128)       │      8,320 │ shared1[0][0]     │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ department_hidden   │ (None, 32)        │      4,128 │ shared2[0][0]     │
│ (Dense)             │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ attrition_hidden    │ (None, 32)        │      4,128 │ shared2[0][0]     │
│ (Dense)             │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ department_output   │ (None, 3)         │         99 │ department_hidde… │
│ (Dense)             │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ attrition_output    │ (None, 2)         │         66 │ attrition_hidden… │
│ (Dense)             │                   │            │                   │
└─────────────────────┴───────────────────┴────────────┴───────────────────┘

 Total params: 17,445 (68.14 KB)

 Trainable params: 17,445 (68.14 KB)

 Non-trainable params: 0 (0.00 B)

In [17]:
# Train the model
model.fit(
    X_train_scaled, 
    {
        'department_output':y_train_department,
        'attrition_output':y_train_attrition
    },
    epochs = 100,
    batch_size = 32,
    validation_split = 0.2
)


Epoch 1/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 5s 27ms/step - attrition_output_accuracy: 0.7459 - attrition_output_mse: 0.2132 - department_output_accuracy: 0.5603 - department_output_mse: 0.1925 - loss: 0.4057 - val_attrition_output_accuracy: 0.8235 - val_attrition_output_mse: 0.1499 - val_department_output_accuracy: 0.6471 - val_department_output_mse: 0.1634 - val_loss: 0.3132
Epoch 2/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - attrition_output_accuracy: 0.8616 - attrition_output_mse: 0.1266 - department_output_accuracy: 0.6281 - department_output_mse: 0.1670 - loss: 0.2936 - val_attrition_output_accuracy: 0.8235 - val_attrition_output_mse: 0.1417 - val_department_output_accuracy: 0.6471 - val_department_output_mse: 0.1621 - val_loss: 0.3038
Epoch 3/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - attrition_output_accuracy: 0.8610 - attrition_output_mse: 0.1131 - department_output_accuracy: 0.6070 - department_output_mse: 0.1691 - loss: 0.2822 - val_attrition_output_accuracy: 0.8235 - val_attr

In [18]:
# Evaluate the model with the testing data

results = model.evaluate(
    X_test_scaled,
    {
        'department_output': y_test_department,
        'attrition_output': y_test_attrition,
    },
    verbose = 2,
    return_dict=True
)

print(results)

12/12 - 0s - 5ms/step - attrition_output_accuracy: 0.8179 - attrition_output_mse: 0.1679 - department_output_accuracy: 0.5353 - department_output_mse: 0.2561 - loss: 0.4240
{'attrition_output_accuracy': 0.8179348111152649, 'attrition_output_mse': 0.16791526973247528, 'department_output_accuracy': 0.5353260636329651, 'department_output_mse': 0.25608035922050476, 'loss': 0.42399564385414124}


In [19]:
# Print the accuracy for both department and attrition
print(f'Department predictions accuracy: {results["department_output_accuracy"]}')
print(f'Attrition predictions accuracy: {results["attrition_output_accuracy"]}')


Department predictions accuracy: 0.5353260636329651
Attrition predictions accuracy: 0.8179348111152649


# Summary

In the provided space below, briefly answer the following questions.

1. Is accuracy the best metric to use on this data? Why or why not?

2. What activation functions did you choose for your output layers, and why?

3. Can you name a few ways that this model might be improved?

YOUR ANSWERS HERE

1. 
2. 
3. 

# 1 -> Accuracy is an acceptable metric, however it appears to be best suited to the binary classification of attriution as opposed to department, which is most likely the result of not having sufficiently relevant data to predict which department someone would wind up in.
# 2 -> the sigmoid function has been selected for the output layer of attrition layer because attrition is a binary poutcome, while the softmax function has been chosen for the department layer output as it contians 3 possible catoegires, the sum total possibilitiues should euqal to 1.
# 3 -> collect more data relevant to predicting which department a given individual would be part of, while predicting attrion may benefit from additioal data related to future job prospects vs economic benefits (i.e. salary).  There are more columns provided int he data set than have been used for the X trainig/test data.  Further analysis would be needed to see if other columns would be more appropriate for increasing the accuracy of either attrition or department predictions.